name: Deploy to dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          fetch-depth: 0

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          bun install

      - name: Build assets
        run: bun run build

      - name: Deploy
        uses: somoscuatro/action-deploy-to-wpengine@main
        env:
          LOCAL_BRANCH: dev
          WPENGINE_ENVIRONMENT_NAME: devsomoscuatro
          WPENGINE_SSH_PRIVATE_KEY: ${{ secrets.WPENGINE_SSH_PRIVATE_KEY }}
          WPENGINE_SSH_PUBLIC_KEY: ${{ secrets.WPENGINE_SSH_PUBLIC_KEY }}
